### PR TITLE
Add substrate api for loader.dylib

### PR DESCRIPTION
**Pull request by zhkl0228**
MIP is great project, thanks.

### CODE REVIEW

**Comment by zhkl0228** [comment]
I have tested substrate api on Intel and ARM macOS.

**Comment by LIJI32** [comment]
Hi, what's the license for Substitute? Can the relevant LICENSE file be added to its directory?

**Comment by zhkl0228** [comment]
https://github.com/comex/substitute/blob/master/LICENSE.txt

**Comment by zhkl0228** [comment]
The substrate api test bundle.
[wechat.zip](https://github.com/LIJI32/MIP/files/9791828/wechat.zip)

**Pull request merged**
